# Generated by Django 4.1 on 2022-09-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_options_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
