# Generated by Django 4.0.7 on 2022-09-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
