# Generated by Django 4.0.7 on 2022-09-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_level_profile_levels'),
        ('posts', '0009_remove_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.level'),
        ),
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
