# Generated by Django 4.0.7 on 2022-09-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_level_post_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile_image',
            new_name='post_image',
        ),
    ]
