# Generated by Django 4.0.7 on 2022-09-13 12:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('church_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('social_Facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('family_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('church', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.church')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='short_intro',
            new_name='social_Facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_youtube',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Makhdom', 'مخدوم'), ('Khadm', 'خادم'), ('Family_head', 'امين اسرة'), ('Priest', 'قس'), ('Archpriest', 'قمص')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.family'),
        ),
    ]
