# Generated by Django 4.0.7 on 2022-09-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_Facebook',
            new_name='social_facebook',
        ),
    ]
