# Generated by Django 4.0.7 on 2022-09-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_family_church'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='social_Facebook',
            new_name='social_facebook',
        ),
    ]
