# Generated by Django 4.1.1 on 2022-09-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_short_into'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_into',
            new_name='short_intro',
        ),
    ]
