# Generated by Django 4.0.7 on 2022-09-25 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0012_rename_short_into_profile_short_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('name', models.CharField(blank=True, choices=[('الاول', 'الاول'), ('الثاني', 'الثاني'), ('الثالث', 'الثالث'), ('الرابع', 'الرابع'), ('الخامس', 'الخامس'), ('السادس', 'السادس'), ('تمهيدي', 'تمهيدي'), ('الكل', 'الكل')], max_length=15, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='family',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.church'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.level'),
        ),
    ]
