# Generated by Django 4.0.7 on 2022-09-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_level_profile_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Educational_qualification',
            field=models.CharField(blank=True, choices=[('المرحلة الإبتدائية', 'المرحلة الإبتدائية'), ('المرحلة الإعدادية', 'المرحلة الإعدادية'), ('الثانوية العامة', 'الثانوية العامة'), ('الثانوي الفنية صنايع', 'الثانوي الفنية صنايع'), ('الثانوي الفنية تجاري', 'الثانوي الفنية تجاري'), ('الثانوي الفنية زراعي', 'الثانوي الفنية زراعي'), ('سباحة وفنادق', 'سباحة وفنادق'), ('الدبلوم', 'الدبلوم'), ('البكالوريوس', 'البكالوريوس'), ('الدبلوم العالي', 'الدبلوم العالي'), ('الماجستير', 'الماجستير'), ('الدكتوراه', 'الدكتوراه')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
