# Generated by Django 4.0.7 on 2022-09-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_educational_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='church',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='data_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, choices=[(0, 'تمهيدي'), (1, 'الاول'), (2, 'الثاني'), (3, 'الثالث'), (4, 'الرابع'), (5, 'الخامس'), (6, 'السادس')], max_length=15, null=True),
        ),
    ]
