# Generated by Django 4.0.7 on 2022-09-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(0, 'تمهيدي'), (1, 'الاول'), (2, 'الثاني'), (3, 'الثالث'), (4, 'الرابع'), (5, 'الخامس'), (6, 'السادس')], default=1),
            preserve_default=False,
        ),
    ]
