# Generated by Django 4.0.7 on 2022-09-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0020_alter_role_id'),
        ('users', '0022_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('group', 'name')},
        ),
    ]
