# Generated by Django 4.0.7 on 2022-09-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_level'),
        ('posts', '0012_alter_post_level'),
        ('books', '0005_alter_book_level'),
        ('quizes', '0024_alter_quiz_level'),
        ('lessons', '0003_alter_lesson_level'),
        ('users', '0023_alter_level_id_alter_level_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='levels',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
