# Generated by Django 4.0.7 on 2022-09-30 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0029_alter_level_unique_together_remove_level_group_and_more'),
        ('users', '0024_remove_profile_levels_delete_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('name', models.CharField(blank=True, choices=[(0, 'تمهيدي'), (1, 'الاول'), (2, 'الثاني'), (3, 'الثالث')], max_length=15, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='levels',
            field=models.ManyToManyField(blank=True, null=True, to='users.level'),
        ),
    ]
