# Generated by Django 4.1 on 2022-09-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
        ('demomethods', '0006_alter_demomethod_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomethod',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
