# Generated by Django 4.1 on 2022-09-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demomethods', '0007_alter_demomethod_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomethod',
            name='tags',
            field=models.ManyToManyField(blank=True, to='demomethods.tag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='demomethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demomethods.demomethod'),
        ),
    ]
