# Generated by Django 4.0.7 on 2022-09-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demomethods', '0008_alter_demomethod_tags_alter_review_demomethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demomethod',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='demomethod',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='demomethod',
            name='vote_total',
        ),
    ]
