# Generated by Django 4.1 on 2022-09-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_file',
            new_name='featured_image',
        ),
    ]
