# Generated by Django 4.0.7 on 2022-09-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_level_profile_levels'),
        ('books', '0003_remove_book_featured_image_book_bookfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.level'),
        ),
        migrations.AddField(
            model_name='book',
            name='public',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
