# Generated by Django 4.0.7 on 2022-09-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_level_profile_levels'),
        ('books', '0005_alter_book_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.level'),
        ),
    ]
