# Generated by Django 4.1 on 2022-09-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='am',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='confession',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='holy_communion',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='liturgy',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='rbible',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
