# Generated by Django 4.1 on 2022-09-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_am_note_confession_note_day_note_holy_communion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='rbible',
            new_name='read_bible',
        ),
    ]
