# Generated by Django 4.1 on 2022-09-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0001_initial'),
        ('notes', '0003_rename_rbible_note_read_bible'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pm',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weeks.week'),
        ),
    ]
