# Generated by Django 4.0.7 on 2022-09-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_pm_note_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='am',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='day',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='holy_communion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='liturgy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='pm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='read_bible',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
