# Generated by Django 4.0.7 on 2022-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_am_alter_note_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='day',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
