# Generated by Django 4.1 on 2022-09-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_result_remove_answer_choice_remove_answer_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz', to='quizes.quiz'),
        ),
    ]
