# Generated by Django 4.1 on 2022-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
