# Generated by Django 4.1 on 2022-09-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_remove_answer_user_userans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='valid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
