# Generated by Django 4.1.1 on 2022-09-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_rename_name_quiz_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='profile_image',
            new_name='questionImage',
        ),
    ]
