# Generated by Django 4.0.7 on 2022-09-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0009_rename_profile_image_question_questionimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionImage',
            new_name='question_image',
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
