# Generated by Django 4.0.7 on 2022-09-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0011_rename_number_of_questions_question_number_of_answers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-valid', '-date']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='number_of_answers',
        ),
    ]
