# Generated by Django 4.0.7 on 2022-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0012_alter_quiz_options_remove_question_number_of_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctAnswers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='wrongAnswers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
