# Generated by Django 4.0.7 on 2022-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_short_into_profile_short_intro'),
        ('quizes', '0013_question_correctanswers_question_wronganswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userans',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userans',
            unique_together={('user', 'question')},
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
