# Generated by Django 4.0.7 on 2022-09-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0017_alter_result_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
