# Generated by Django 4.0.7 on 2022-09-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0018_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
