# Generated by Django 4.0.7 on 2022-09-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_username'),
        ('quizes', '0020_quiz_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='level',
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.ManyToManyField(blank=True, null=True, to='users.level'),
        ),
    ]
