# Generated by Django 4.1 on 2022-09-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
