# Generated by Django 4.1.1 on 2022-09-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
