# Generated by Django 4.0.7 on 2022-09-28 15:15

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0021_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'lesson'), (2, 'وسائل الايضاح'), (3, 'الطقس'), (4, 'لغة قبطية'), (5, 'الألحان'), (6, 'الكتاب المقدس'), (7, 'اللاهوت'), (8, 'عقيدة'), (9, 'التاريخ الكنسي')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='lessons/')),
                ('public', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_to', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.level')),
                ('type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lessontype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
