# Generated by Django 4.0.7 on 2022-09-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lessontype'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'post'), (2, 'وسائل الايضاح'), (3, 'الطقس'), (4, 'لغة قبطية'), (5, 'الألحان'), (6, 'الكتاب المقدس'), (7, 'اللاهوت'), (8, 'عقيدة'), (9, 'التاريخ الكنسي')], primary_key=True, serialize=False),
        ),
    ]
